name: Fetch data
on:
  schedule:
    - cron: '*/3 10-19 * * 1-5'

      branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    steps:
      - name: Run python program on github agent
        run: |
          docker run -e DB_USERNAME -e DB_NAME -e DB_PASSWORD $DOCKER_HUB_USERNAME/dev-app-daily:latest